# coding: utf-8

"""
    user-service

    User Management Service

    The version of the OpenAPI document: 0.03
    Contact: overparser@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.users_api import UsersApi  # noqa: E501


class TestUsersApi(unittest.IsolatedAsyncioTestCase):
    """UsersApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = UsersApi()

    async def asyncTearDown(self) -> None:
        pass

    async def test_delete_users_user_id(self) -> None:
        """Test case for delete_users_user_id

        Delete User  # noqa: E501
        """
        pass

    async def test_get_users_user_id(self) -> None:
        """Test case for get_users_user_id

        Get User Info by User ID  # noqa: E501
        """
        pass

    async def test_patch_users_user_id(self) -> None:
        """Test case for patch_users_user_id

        Update User Information  # noqa: E501
        """
        pass

    async def test_post_user(self) -> None:
        """Test case for post_user

        Create New User  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
