# coding: utf-8

# flake8: noqa
"""
    user-service

    User Management Service

    The version of the OpenAPI document: 0.03
    Contact: derror.dd@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.error import Error
from openapi_client.models.get_health200_response import GetHealth200Response
from openapi_client.models.get_users_user_id404_response import GetUsersUserId404Response
from openapi_client.models.get_users_user_id404_response_error import GetUsersUserId404ResponseError
from openapi_client.models.patch_users_user_id_request import PatchUsersUserIdRequest
from openapi_client.models.post_user_request import PostUserRequest
from openapi_client.models.user import User
from openapi_client.models.user_preferences import UserPreferences
