# coding: utf-8

"""
    user-service

    User Management Service

    The version of the OpenAPI document: 0.03
    Contact: derror.dd@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel
from openapi_client.models.get_users_user_id404_response_error import GetUsersUserId404ResponseError

class GetUsersUserId404Response(BaseModel):
    """
    GetUsersUserId404Response
    """
    error: Optional[GetUsersUserId404ResponseError] = None
    __properties = ["error"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GetUsersUserId404Response:
        """Create an instance of GetUsersUserId404Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of error
        if self.error:
            _dict['error'] = self.error.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GetUsersUserId404Response:
        """Create an instance of GetUsersUserId404Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GetUsersUserId404Response.parse_obj(obj)

        _obj = GetUsersUserId404Response.parse_obj({
            "error": GetUsersUserId404ResponseError.from_dict(obj.get("error")) if obj.get("error") is not None else None
        })
        return _obj


