# coding: utf-8

"""
    user-service

    User Management Service

    The version of the OpenAPI document: 0.03
    Contact: derror.dd@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictStr

class GetHealth200Response(BaseModel):
    """
    GetHealth200Response
    """
    status: Optional[StrictStr] = 'OK'
    __properties = ["status"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GetHealth200Response:
        """Create an instance of GetHealth200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GetHealth200Response:
        """Create an instance of GetHealth200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GetHealth200Response.parse_obj(obj)

        _obj = GetHealth200Response.parse_obj({
            "status": obj.get("status") if obj.get("status") is not None else 'OK'
        })
        return _obj


