# coding: utf-8

# flake8: noqa

"""
    user-service

    User Management Service

    The version of the OpenAPI document: 0.03
    Contact: overparser@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.health_api import HealthApi
from openapi_client.api.users_api import UsersApi

# import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiAttributeError
from openapi_client.exceptions import ApiException

# import models into sdk package
from openapi_client.models.error import Error
from openapi_client.models.get_health200_response import GetHealth200Response
from openapi_client.models.get_users_user_id404_response import GetUsersUserId404Response
from openapi_client.models.get_users_user_id404_response_error import GetUsersUserId404ResponseError
from openapi_client.models.patch_users_user_id_request import PatchUsersUserIdRequest
from openapi_client.models.post_user_request import PostUserRequest
from openapi_client.models.user import User
from openapi_client.models.user_preferences import UserPreferences
